In [19]:
import numpy as np
import scipy.linalg as ln

np.set_printoptions(threshold=np.inf)
a = np.zeros((64,64))

for i in range(0, 8):
    for j in range(0, 8):
        ma = np.zeros((8,8))
        ma[i][j] = 1
        if(i>0):
            ma[i-1][j] = 1
        if(i<7):
            ma[i+1][j] = 1
        if(j>0):
            ma[i][j-1] = 1
        if(j<7):
            ma[i][j+1] = 1
        a[:,8*i+j] = np.concatenate(ma)
        
def savemat(mat,name):
    s = '{'
    n = mat.shape[0]
    for i in range(0,n):
        s += '{'
        for j in range(0,n):
            s += '%u,' %(mat[i][j])
        s+= '},'
    s = s[:-1]
    s += '}'
    f = open(name,'w')
    f.write(s)

savemat(a,'moves.dat')
    
def gauss(A,b):
    ma = A
    be = b
    n = b.shape[0]
    inv = np.eye(n)
    for j in range(0,n):
        idx = int(np.argwhere(ma[j,:]==1)[0])
        #print type(idx)
        ind = np.argwhere(ma[:,idx]==1)
        #print 'id',ind
        ind = ind[np.where(ind != idx)]
        #print 'idx', idx
        #print 'ind', ind
        for k in ind:
            ma[k,:] = np.int_(np.logical_xor(ma[k,:],ma[idx,:]))
            be[k] = np.int_(np.logical_xor(b[k],b[idx]))
            inv[k,:] = np.int_(np.logical_xor(inv[k,:],inv[idx,:]))
    for j in range(0,n):
        idx = int(np.argwhere(ma[j,:]==1)[0])
        #print type(idx)
        ind = np.argwhere(ma[:,idx]==1)
        #print 'id',ind
        ind = ind[np.where(ind != idx)]
        #print 'idx', idx
        #print 'ind', ind
        for k in ind:
            ma[k,:] = np.int_(np.logical_xor(ma[k,:],ma[idx,:]))
            be[k] = np.int_(np.logical_xor(b[k],b[idx]))
            inv[k,:] = np.int_(np.logical_xor(inv[k,:],inv[idx,:]))
    for j in range(0,n):
        idx = int(np.argwhere(ma[j,:]==1)[0])
        #print type(idx)
        ind = np.argwhere(ma[:,idx]==1)
        #print 'id',ind
        ind = ind[np.where(ind != idx)]
        #print 'idx', idx
        #print 'ind', ind
        for k in ind:
            ma[k,:] = np.int_(np.logical_xor(ma[k,:],ma[idx,:]))
            be[k] = np.int_(np.logical_xor(b[k],b[idx]))
            inv[k,:] = np.int_(np.logical_xor(inv[k,:],inv[idx,:]))
    for j in range(0,n):
        idx = int(np.argwhere(ma[j,:]==1)[0])
        #print type(idx)
        ind = np.argwhere(ma[:,idx]==1)
        #print 'id',ind
        ind = ind[np.where(ind != idx)]
        #print 'idx', idx
        #print 'ind', ind
        for k in ind:
            ma[k,:] = np.int_(np.logical_xor(ma[k,:],ma[idx,:]))
            be[k] = np.int_(np.logical_xor(b[k],b[idx]))
            inv[k,:] = np.int_(np.logical_xor(inv[k,:],inv[idx,:]))
    
    #ma = ma[::-1]
    #be = be[::-1]
    test = ma==np.eye(64)
    return ma, be, test, inv

var, y, p, inv = gauss(a,np.ones(64))
savemat(inv,'inverse.dat')
print inv

[[ 1.  1.  0.  1.  1.  1.  0.  0.  1.  0.  0.  0.  1.  0.  1.  0.  0.  0.
   0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.
   0.  1.  1.  1.  1.  0.  1.  0.  1.  0.  1.  0.  0.  1.  1.  0.  1.  1.
   0.  0.  0.  0.  1.  0.  1.  0.  0.  0.]
 [ 1.  1.  0.  1.  0.  1.  1.  0.  0.  1.  0.  1.  0.  0.  0.  1.  0.  0.
   0.  0.  1.  1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  1.  0.
   1.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  1.  1.
   1.  0.  0.  1.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  1.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.  1.  0.  1.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.
   1.  0.  1.  1.  1.  0.  1.  0.  1.  0.  0.  0.  1.  1.  0.  0.  0.  1.
   1.  1.  1.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  1.  1.  0.  1.  1.  0.  1.  0.  1.  0.  1.  0.  0.  0.  1.  0.  0.
   1.  1.  0.  1.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  1.  0.  0.

In [2]:
k = np.ones((4,4))-np.eye(4)[::-1]
solp, xp, test, inve = gauss(k,np.array([0,0,0,1]))
print solp, xp, test, inve

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]] [0 1 1 1] False [[ 1.  1.  1.  0.]
 [ 1.  1.  0.  1.]
 [ 1.  0.  1.  1.]
 [ 0.  1.  1.  1.]]


In [95]:
a = np.array([1,0,0,1,0,1,0])
ind = [i for i, x in enumerate(a) if x==1]
ind.pop(ind.index(3))
print ind

[0, 5]


In [88]:
a = np.array([0,1,2,3,4,5])
h = a[np.where(a!=3)]
k = h[::-1]
print k
print k[0,3,1,2]

[5 4 2 1 0]


IndexError: too many indices for array

In [108]:
a = np.eye(4)
print gauss(a,np.ones(4))

<type 'int'>
id [[0]]
idx 0
ind []
<type 'int'>
id [[1]]
idx 1
ind []
<type 'int'>
id [[2]]
idx 2
ind []
<type 'int'>
id [[3]]
idx 3
ind []
(array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]]), array([ 1.,  1.,  1.,  1.]), False)


In [12]:
a = np.zeros((49,49))

for i in range(0, 7):
    for j in range(0, 7):
        ma = np.zeros((7,7))
        ma[i][j] = 1
        if(i>0):
            ma[i-1][j] = 1
        if(i<6):
            ma[i+1][j] = 1
        if(j>0):
            ma[i][j-1] = 1
        if(j<2):
            ma[i][j+1] = 1
        a[:,2*i+j] = np.concatenate(ma)
arr = np.ones(9)
print arr.shape
solp, xp, test, inve = gauss(a,arr)
print solp, xp, test, inve

(9L,)


IndexError: index 0 is out of bounds for axis 0 with size 0